# app/config/security.yml
security:
    encoders:
        Aet\AnnuaireBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
            # … le pare-feu « dev »
            # Firewall principal pour le reste de notre site
            dev:
                        pattern: ^/(_(profiler|wdt))/
                        security: false
            main:
               pattern: ^/
               form_login:
                   provider:       fos_userbundle
                   csrf_provider: form.csrf_provider
               logout:       true
               anonymous:    true
               remember_me:
                               key:             %secret%        # On définit la clé pour le remember_me (%secret% est un parametre de parameters.yml)
                         #         lifetime:        300             # 15min en secondes

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    acl:
        connection: default