Aet\AnnuaireBundle\Entity\Author:
    properties:
        matricule:
            - Type:
                type: numeric
                message: La valeur {{ value }} n'est pas un type {{ type }} valide.