<?php

namespace Aet\AnnuaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AetImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AetImageRepository extends EntityRepository
{
}
