<?php

namespace Aet\AnnuaireBundle\Entity;

/**
 * AetPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AetPageRepository extends \Doctrine\ORM\EntityRepository
{
}
