<?php

namespace Aet\AnnuaireBundle\Entity;

use Doctrine\ORM\EntityRepository;
//use FOS\ElasticaBundle\Repository;

/**
 * User_AetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAetRepository extends EntityRepository
{

}
